CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "ProfilePictureUrl" character varying(75),
    "FirstName" character varying(75) NOT NULL,
    "LastName" character varying(75) NOT NULL,
    "NameSuffix" character varying(75),
    "DateOfBirth" date,
    "City" character varying(75),
    "State" character varying(75),
    "Occupation" character varying(75),
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);


CREATE TABLE "AuditLogs" (
    "Id" bigint NOT NULL,
    "ActionStamp" timestamp with time zone NOT NULL,
    "UserId" character varying(450) NOT NULL,
    "ActionCategory" character varying(100) NOT NULL,
    "ActionDetails" TEXT NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id", "ActionStamp")
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Friendships" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RequesterId" text NOT NULL,
    "AddresseeId" text NOT NULL,
    "Status" integer NOT NULL,
    "RequestedAt" timestamp with time zone NOT NULL,
    "RespondedAt" timestamp with time zone,
    CONSTRAINT "PK_Friendships" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Friendships_AspNetUsers_AddresseeId" FOREIGN KEY ("AddresseeId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Friendships_AspNetUsers_RequesterId" FOREIGN KEY ("RequesterId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Groups" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsPublic" boolean NOT NULL,
    "IsHidden" boolean NOT NULL,
    "LastActiveAt" timestamp with time zone NOT NULL,
    "MemberCount" integer NOT NULL,
    "RequiresJoinApproval" boolean NOT NULL,
    "RequireAcceptRules" boolean NOT NULL,
    "RequiresPostApproval" boolean NOT NULL,
    "EnablePointsSystem" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsClosed" boolean NOT NULL,
    "CreatorId" text NOT NULL,
    "HeaderImageUrl" character varying(500),
    "VerticalHeaderImageUrl" character varying(500),
    "WebsiteUrl" character varying(500),
    CONSTRAINT "PK_Groups" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Groups_AspNetUsers_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Posts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AuthorId" text NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "LikeCount" integer NOT NULL,
    "CommentCount" integer NOT NULL,
    "ShareCount" integer NOT NULL,
    "AudienceType" integer NOT NULL,
    CONSTRAINT "PK_Posts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Posts_AspNetUsers_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "UserNotifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Type" integer NOT NULL,
    "TemplateKey" text,
    "Message" text NOT NULL,
    "Data" text,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone,
    CONSTRAINT "PK_UserNotifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserNotifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserPreferences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "PreferenceType" integer NOT NULL,
    "PreferenceValue" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserPreferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserPreferences_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupBannedMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupId" integer NOT NULL,
    "UserId" text NOT NULL,
    "BannedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GroupBannedMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupBannedMembers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GroupBannedMembers_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupJoinRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupId" integer NOT NULL,
    "UserId" text NOT NULL,
    "RequestedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GroupJoinRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupJoinRequests_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GroupJoinRequests_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupPosts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupId" integer NOT NULL,
    "AuthorId" text NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "LikeCount" integer NOT NULL,
    "CommentCount" integer NOT NULL,
    "ShareCount" integer NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_GroupPosts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupPosts_AspNetUsers_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_GroupPosts_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupRules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "Order" integer NOT NULL,
    CONSTRAINT "PK_GroupRules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupRules_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupId" integer NOT NULL,
    "UserId" text NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    "PostCount" integer NOT NULL,
    "GroupPoints" integer NOT NULL,
    "IsAdmin" boolean NOT NULL,
    "IsModerator" boolean NOT NULL,
    "LastActiveAt" timestamp with time zone NOT NULL,
    "HasAgreedToRules" boolean NOT NULL,
    CONSTRAINT "PK_GroupUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupUsers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GroupUsers_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Comments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostId" integer NOT NULL,
    "AuthorId" text NOT NULL,
    "Content" text NOT NULL,
    "ImageUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ParentCommentId" integer,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_AspNetUsers_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Comments_Comments_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES "Comments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Comments_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Likes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Likes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Likes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Likes_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PinnedPosts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "PostId" integer NOT NULL,
    "PinnedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PinnedPosts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PinnedPosts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PinnedPosts_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PostImages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostId" integer NOT NULL,
    "ImageUrl" text NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PostImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PostImages_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PostNotificationMutes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostId" integer NOT NULL,
    "UserId" text NOT NULL,
    "MutedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PostNotificationMutes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PostNotificationMutes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PostNotificationMutes_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupPostComments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostId" integer NOT NULL,
    "AuthorId" text NOT NULL,
    "Content" text NOT NULL,
    "ImageUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ParentCommentId" integer,
    CONSTRAINT "PK_GroupPostComments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupPostComments_AspNetUsers_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_GroupPostComments_GroupPostComments_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES "GroupPostComments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GroupPostComments_GroupPosts_PostId" FOREIGN KEY ("PostId") REFERENCES "GroupPosts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupPostImages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostId" integer NOT NULL,
    "ImageUrl" text NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GroupPostImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupPostImages_GroupPosts_PostId" FOREIGN KEY ("PostId") REFERENCES "GroupPosts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupPostLikes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GroupPostLikes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupPostLikes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GroupPostLikes_GroupPosts_PostId" FOREIGN KEY ("PostId") REFERENCES "GroupPosts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupPostNotificationMutes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostId" integer NOT NULL,
    "UserId" text NOT NULL,
    "MutedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GroupPostNotificationMutes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupPostNotificationMutes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GroupPostNotificationMutes_GroupPosts_PostId" FOREIGN KEY ("PostId") REFERENCES "GroupPosts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PinnedGroupPosts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "PostId" integer NOT NULL,
    "PinnedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PinnedGroupPosts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PinnedGroupPosts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PinnedGroupPosts_GroupPosts_PostId" FOREIGN KEY ("PostId") REFERENCES "GroupPosts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "CommentLikes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CommentId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CommentLikes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CommentLikes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CommentLikes_Comments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "Comments" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupContentReports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupId" integer NOT NULL,
    "PostId" integer,
    "CommentId" integer,
    "ReporterId" text NOT NULL,
    "Reason" integer NOT NULL,
    "ViolatedRuleId" integer,
    "Description" character varying(2000),
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReviewerId" text,
    "ReviewedAt" timestamp with time zone,
    "ReviewerNotes" character varying(2000),
    CONSTRAINT "PK_GroupContentReports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupContentReports_AspNetUsers_ReporterId" FOREIGN KEY ("ReporterId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_GroupContentReports_AspNetUsers_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_GroupContentReports_GroupPostComments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "GroupPostComments" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_GroupContentReports_GroupPosts_PostId" FOREIGN KEY ("PostId") REFERENCES "GroupPosts" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_GroupContentReports_GroupRules_ViolatedRuleId" FOREIGN KEY ("ViolatedRuleId") REFERENCES "GroupRules" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_GroupContentReports_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE
);


CREATE TABLE "GroupPostCommentLikes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CommentId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GroupPostCommentLikes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupPostCommentLikes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GroupPostCommentLikes_GroupPostComments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "GroupPostComments" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE INDEX "IX_AuditLogs_ActionCategory" ON "AuditLogs" ("ActionCategory");


CREATE INDEX "IX_AuditLogs_ActionStamp" ON "AuditLogs" ("ActionStamp");


CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");


CREATE INDEX "IX_AuditLogs_UserId_ActionStamp" ON "AuditLogs" ("UserId", "ActionStamp");


CREATE INDEX "IX_CommentLikes_CommentId" ON "CommentLikes" ("CommentId");


CREATE UNIQUE INDEX "IX_CommentLikes_CommentId_UserId" ON "CommentLikes" ("CommentId", "UserId");


CREATE INDEX "IX_CommentLikes_UserId" ON "CommentLikes" ("UserId");


CREATE INDEX "IX_Comments_AuthorId" ON "Comments" ("AuthorId");


CREATE INDEX "IX_Comments_CreatedAt" ON "Comments" ("CreatedAt");


CREATE INDEX "IX_Comments_ParentCommentId" ON "Comments" ("ParentCommentId");


CREATE INDEX "IX_Comments_PostId" ON "Comments" ("PostId");


CREATE INDEX "IX_Friendships_AddresseeId" ON "Friendships" ("AddresseeId");


CREATE INDEX "IX_Friendships_RequesterId" ON "Friendships" ("RequesterId");


CREATE UNIQUE INDEX "IX_Friendships_RequesterId_AddresseeId" ON "Friendships" ("RequesterId", "AddresseeId");


CREATE INDEX "IX_Friendships_Status" ON "Friendships" ("Status");


CREATE INDEX "IX_Friendships_Status_AddresseeId" ON "Friendships" ("Status", "AddresseeId");


CREATE INDEX "IX_Friendships_Status_RequesterId" ON "Friendships" ("Status", "RequesterId");


CREATE INDEX "IX_GroupBannedMembers_BannedAt" ON "GroupBannedMembers" ("BannedAt");


CREATE INDEX "IX_GroupBannedMembers_GroupId" ON "GroupBannedMembers" ("GroupId");


CREATE UNIQUE INDEX "IX_GroupBannedMembers_GroupId_UserId" ON "GroupBannedMembers" ("GroupId", "UserId");


CREATE INDEX "IX_GroupBannedMembers_UserId" ON "GroupBannedMembers" ("UserId");


CREATE INDEX "IX_GroupContentReports_CommentId" ON "GroupContentReports" ("CommentId");


CREATE INDEX "IX_GroupContentReports_CreatedAt" ON "GroupContentReports" ("CreatedAt");


CREATE INDEX "IX_GroupContentReports_GroupId" ON "GroupContentReports" ("GroupId");


CREATE INDEX "IX_GroupContentReports_GroupId_Status" ON "GroupContentReports" ("GroupId", "Status");


CREATE INDEX "IX_GroupContentReports_PostId" ON "GroupContentReports" ("PostId");


CREATE INDEX "IX_GroupContentReports_ReporterId" ON "GroupContentReports" ("ReporterId");


CREATE INDEX "IX_GroupContentReports_ReviewerId" ON "GroupContentReports" ("ReviewerId");


CREATE INDEX "IX_GroupContentReports_Status" ON "GroupContentReports" ("Status");


CREATE INDEX "IX_GroupContentReports_ViolatedRuleId" ON "GroupContentReports" ("ViolatedRuleId");


CREATE INDEX "IX_GroupJoinRequests_GroupId" ON "GroupJoinRequests" ("GroupId");


CREATE UNIQUE INDEX "IX_GroupJoinRequests_GroupId_UserId" ON "GroupJoinRequests" ("GroupId", "UserId");


CREATE INDEX "IX_GroupJoinRequests_RequestedAt" ON "GroupJoinRequests" ("RequestedAt");


CREATE INDEX "IX_GroupJoinRequests_UserId" ON "GroupJoinRequests" ("UserId");


CREATE INDEX "IX_GroupPostCommentLikes_CommentId" ON "GroupPostCommentLikes" ("CommentId");


CREATE UNIQUE INDEX "IX_GroupPostCommentLikes_CommentId_UserId" ON "GroupPostCommentLikes" ("CommentId", "UserId");


CREATE INDEX "IX_GroupPostCommentLikes_UserId" ON "GroupPostCommentLikes" ("UserId");


CREATE INDEX "IX_GroupPostComments_AuthorId" ON "GroupPostComments" ("AuthorId");


CREATE INDEX "IX_GroupPostComments_CreatedAt" ON "GroupPostComments" ("CreatedAt");


CREATE INDEX "IX_GroupPostComments_ParentCommentId" ON "GroupPostComments" ("ParentCommentId");


CREATE INDEX "IX_GroupPostComments_PostId" ON "GroupPostComments" ("PostId");


CREATE INDEX "IX_GroupPostImages_PostId" ON "GroupPostImages" ("PostId");


CREATE INDEX "IX_GroupPostImages_PostId_DisplayOrder" ON "GroupPostImages" ("PostId", "DisplayOrder");


CREATE INDEX "IX_GroupPostLikes_PostId" ON "GroupPostLikes" ("PostId");


CREATE UNIQUE INDEX "IX_GroupPostLikes_PostId_UserId" ON "GroupPostLikes" ("PostId", "UserId");


CREATE INDEX "IX_GroupPostLikes_UserId" ON "GroupPostLikes" ("UserId");


CREATE INDEX "IX_GroupPostNotificationMutes_PostId" ON "GroupPostNotificationMutes" ("PostId");


CREATE UNIQUE INDEX "IX_GroupPostNotificationMutes_PostId_UserId" ON "GroupPostNotificationMutes" ("PostId", "UserId");


CREATE INDEX "IX_GroupPostNotificationMutes_UserId" ON "GroupPostNotificationMutes" ("UserId");


CREATE INDEX "IX_GroupPosts_AuthorId" ON "GroupPosts" ("AuthorId");


CREATE INDEX "IX_GroupPosts_CreatedAt" ON "GroupPosts" ("CreatedAt");


CREATE INDEX "IX_GroupPosts_GroupId" ON "GroupPosts" ("GroupId");


CREATE INDEX "IX_GroupPosts_GroupId_CreatedAt" ON "GroupPosts" ("GroupId", "CreatedAt");


CREATE INDEX "IX_GroupRules_GroupId" ON "GroupRules" ("GroupId");


CREATE INDEX "IX_GroupRules_GroupId_Order" ON "GroupRules" ("GroupId", "Order");


CREATE INDEX "IX_Groups_CreatedAt" ON "Groups" ("CreatedAt");


CREATE INDEX "IX_Groups_CreatorId" ON "Groups" ("CreatorId");


CREATE INDEX "IX_Groups_IsHidden" ON "Groups" ("IsHidden");


CREATE INDEX "IX_Groups_IsPublic" ON "Groups" ("IsPublic");


CREATE INDEX "IX_Groups_IsPublic_IsHidden_LastActiveAt" ON "Groups" ("IsPublic", "IsHidden", "LastActiveAt");


CREATE INDEX "IX_Groups_LastActiveAt" ON "Groups" ("LastActiveAt");


CREATE INDEX "IX_Groups_Name" ON "Groups" ("Name");


CREATE INDEX "IX_GroupUsers_GroupId" ON "GroupUsers" ("GroupId");


CREATE INDEX "IX_GroupUsers_GroupId_IsAdmin_IsModerator" ON "GroupUsers" ("GroupId", "IsAdmin", "IsModerator");


CREATE UNIQUE INDEX "IX_GroupUsers_GroupId_UserId" ON "GroupUsers" ("GroupId", "UserId");


CREATE INDEX "IX_GroupUsers_IsAdmin" ON "GroupUsers" ("IsAdmin");


CREATE INDEX "IX_GroupUsers_IsModerator" ON "GroupUsers" ("IsModerator");


CREATE INDEX "IX_GroupUsers_JoinedAt" ON "GroupUsers" ("JoinedAt");


CREATE INDEX "IX_GroupUsers_LastActiveAt" ON "GroupUsers" ("LastActiveAt");


CREATE INDEX "IX_GroupUsers_UserId" ON "GroupUsers" ("UserId");


CREATE INDEX "IX_Likes_PostId" ON "Likes" ("PostId");


CREATE UNIQUE INDEX "IX_Likes_PostId_UserId" ON "Likes" ("PostId", "UserId");


CREATE INDEX "IX_Likes_UserId" ON "Likes" ("UserId");


CREATE INDEX "IX_PinnedGroupPosts_PinnedAt" ON "PinnedGroupPosts" ("PinnedAt");


CREATE INDEX "IX_PinnedGroupPosts_PostId" ON "PinnedGroupPosts" ("PostId");


CREATE INDEX "IX_PinnedGroupPosts_UserId" ON "PinnedGroupPosts" ("UserId");


CREATE UNIQUE INDEX "IX_PinnedGroupPosts_UserId_PostId" ON "PinnedGroupPosts" ("UserId", "PostId");


CREATE INDEX "IX_PinnedPosts_PinnedAt" ON "PinnedPosts" ("PinnedAt");


CREATE INDEX "IX_PinnedPosts_PostId" ON "PinnedPosts" ("PostId");


CREATE INDEX "IX_PinnedPosts_UserId" ON "PinnedPosts" ("UserId");


CREATE UNIQUE INDEX "IX_PinnedPosts_UserId_PostId" ON "PinnedPosts" ("UserId", "PostId");


CREATE INDEX "IX_PostImages_PostId" ON "PostImages" ("PostId");


CREATE INDEX "IX_PostImages_PostId_DisplayOrder" ON "PostImages" ("PostId", "DisplayOrder");


CREATE INDEX "IX_PostNotificationMutes_PostId" ON "PostNotificationMutes" ("PostId");


CREATE UNIQUE INDEX "IX_PostNotificationMutes_PostId_UserId" ON "PostNotificationMutes" ("PostId", "UserId");


CREATE INDEX "IX_PostNotificationMutes_UserId" ON "PostNotificationMutes" ("UserId");


CREATE INDEX "IX_Posts_AuthorId" ON "Posts" ("AuthorId");


CREATE INDEX "IX_Posts_AuthorId_AudienceType_CreatedAt" ON "Posts" ("AuthorId", "AudienceType", "CreatedAt");


CREATE INDEX "IX_Posts_CreatedAt" ON "Posts" ("CreatedAt");


CREATE INDEX "IX_UserNotifications_CreatedAt" ON "UserNotifications" ("CreatedAt");


CREATE INDEX "IX_UserNotifications_ExpiresAt" ON "UserNotifications" ("ExpiresAt");


CREATE INDEX "IX_UserNotifications_IsRead" ON "UserNotifications" ("IsRead");


CREATE INDEX "IX_UserNotifications_Type" ON "UserNotifications" ("Type");


CREATE INDEX "IX_UserNotifications_UserId" ON "UserNotifications" ("UserId");


CREATE INDEX "IX_UserNotifications_UserId_IsRead_CreatedAt" ON "UserNotifications" ("UserId", "IsRead", "CreatedAt");


CREATE INDEX "IX_UserPreferences_PreferenceType" ON "UserPreferences" ("PreferenceType");


CREATE INDEX "IX_UserPreferences_UserId" ON "UserPreferences" ("UserId");


CREATE UNIQUE INDEX "IX_UserPreferences_UserId_PreferenceType" ON "UserPreferences" ("UserId", "PreferenceType");


