//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Pages {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FriendDetails {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FriendDetails() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Pages.FriendDetails", typeof(FriendDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Friend not found..
        /// </summary>
        public static string FriendNotFound {
            get {
                return ResourceManager.GetString("FriendNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string FriendPosts {
            get {
                return ResourceManager.GetString("FriendPosts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Load More Posts.
        /// </summary>
        public static string LoadMorePosts {
            get {
                return ResourceManager.GetString("LoadMorePosts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading friend information....
        /// </summary>
        public static string LoadingFriendInformation {
            get {
                return ResourceManager.GetString("LoadingFriendInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading more posts....
        /// </summary>
        public static string LoadingMorePosts {
            get {
                return ResourceManager.GetString("LoadingMorePosts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading posts....
        /// </summary>
        public static string LoadingPosts {
            get {
                return ResourceManager.GetString("LoadingPosts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This friend hasn't shared any posts yet..
        /// </summary>
        public static string NoPostsMessage {
            get {
                return ResourceManager.GetString("NoPostsMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No posts yet.
        /// </summary>
        public static string NoPostsYet {
            get {
                return ResourceManager.GetString("NoPostsYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No more posts at this time.
        /// </summary>
        public static string NoMorePosts {
            get {
                return ResourceManager.GetString("NoMorePosts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are not friends with this user..
        /// </summary>
        public static string NotFriends {
            get {
                return ResourceManager.GetString("NotFriends", resourceCulture);
            }
        }
    }
}