//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Pages {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyUploads {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyUploads() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Pages.MyUploads", typeof(MyUploads).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You've reached the end of your pictures.
        /// </summary>
        public static string EndOfPictures {
            get {
                return ResourceManager.GetString("EndOfPictures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You've reached the end of your videos.
        /// </summary>
        public static string EndOfVideos {
            get {
                return ResourceManager.GetString("EndOfVideos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading more....
        /// </summary>
        public static string LoadingMore {
            get {
                return ResourceManager.GetString("LoadingMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading your pictures....
        /// </summary>
        public static string LoadingPictures {
            get {
                return ResourceManager.GetString("LoadingPictures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading your videos....
        /// </summary>
        public static string LoadingVideos {
            get {
                return ResourceManager.GetString("LoadingVideos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pictures you upload with your posts will appear here..
        /// </summary>
        public static string NoPicturesDescription {
            get {
                return ResourceManager.GetString("NoPicturesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No pictures yet.
        /// </summary>
        public static string NoPicturesYet {
            get {
                return ResourceManager.GetString("NoPicturesYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Videos you upload with your posts will appear here..
        /// </summary>
        public static string NoVideosDescription {
            get {
                return ResourceManager.GetString("NoVideosDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No videos yet.
        /// </summary>
        public static string NoVideosYet {
            get {
                return ResourceManager.GetString("NoVideosYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other file types will appear here in the future..
        /// </summary>
        public static string OtherFilesDescription {
            get {
                return ResourceManager.GetString("OtherFilesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Uploads.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Uploads.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
    }
}
