//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Pages {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemModerator {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemModerator() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Pages.SystemModerator", typeof(SystemModerator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string PageTitle { get { return ResourceManager.GetString("PageTitle", resourceCulture); } }
        public static string Heading { get { return ResourceManager.GetString("Heading", resourceCulture); } }
        public static string WelcomeGreeting { get { return ResourceManager.GetString("WelcomeGreeting", resourceCulture); } }
        public static string WelcomeMessage { get { return ResourceManager.GetString("WelcomeMessage", resourceCulture); } }
        public static string AvailableFunctions { get { return ResourceManager.GetString("AvailableFunctions", resourceCulture); } }
        public static string FunctionsDescription { get { return ResourceManager.GetString("FunctionsDescription", resourceCulture); } }
        public static string ContentModerationQueue { get { return ResourceManager.GetString("ContentModerationQueue", resourceCulture); } }
        public static string UserReportsReview { get { return ResourceManager.GetString("UserReportsReview", resourceCulture); } }
        public static string FlaggedPostsManagement { get { return ResourceManager.GetString("FlaggedPostsManagement", resourceCulture); } }
        public static string CommunityGuidelineEnforcement { get { return ResourceManager.GetString("CommunityGuidelineEnforcement", resourceCulture); } }
        public static string UserWarningsAndSuspensions { get { return ResourceManager.GetString("UserWarningsAndSuspensions", resourceCulture); } }
        public static string ModerationActivityLogs { get { return ResourceManager.GetString("ModerationActivityLogs", resourceCulture); } }
        public static string YourInformation { get { return ResourceManager.GetString("YourInformation", resourceCulture); } }
        public static string Username { get { return ResourceManager.GetString("Username", resourceCulture); } }
        public static string Email { get { return ResourceManager.GetString("Email", resourceCulture); } }
        public static string Roles { get { return ResourceManager.GetString("Roles", resourceCulture); } }
    }
}
