//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Account.Shared {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserPreferencesComponent {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserPreferencesComponent() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Account.Shared.UserPreferencesComponent", typeof(UserPreferencesComponent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Public (Everyone can see).
        /// </summary>
        public static string AudiencePublic {
            get {
                return ResourceManager.GetString("AudiencePublic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Friends Only.
        /// </summary>
        public static string AudienceFriendsOnly {
            get {
                return ResourceManager.GetString("AudienceFriendsOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only Me (Private).
        /// </summary>
        public static string AudienceMeOnly {
            get {
                return ResourceManager.GetString("AudienceMeOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color Scheme.
        /// </summary>
        public static string ColorScheme {
            get {
                return ResourceManager.GetString("ColorScheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred color theme for the site..
        /// </summary>
        public static string ColorSchemeHelpText {
            get {
                return ResourceManager.GetString("ColorSchemeHelpText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment Reactions.
        /// </summary>
        public static string CommentReactions {
            get {
                return ResourceManager.GetString("CommentReactions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment Replies.
        /// </summary>
        public static string CommentReplies {
            get {
                return ResourceManager.GetString("CommentReplies", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your country or region..
        /// </summary>
        public static string CountryHelpText {
            get {
                return ResourceManager.GetString("CountryHelpText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default Post Visibility.
        /// </summary>
        public static string DefaultPostVisibility {
            get {
                return ResourceManager.GetString("DefaultPostVisibility", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default visibility for new posts. You can change this when creating a post..
        /// </summary>
        public static string DefaultPostVisibilityHelpText {
            get {
                return ResourceManager.GetString("DefaultPostVisibilityHelpText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading your preferences..
        /// </summary>
        public static string ErrorLoadingPreferences {
            get {
                return ResourceManager.GetString("ErrorLoadingPreferences", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving your preferences. Please try again..
        /// </summary>
        public static string ErrorSavingPreferences {
            get {
                return ResourceManager.GetString("ErrorSavingPreferences", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Friend Accepted.
        /// </summary>
        public static string FriendAccepted {
            get {
                return ResourceManager.GetString("FriendAccepted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Friend Requests.
        /// </summary>
        public static string FriendRequests {
            get {
                return ResourceManager.GetString("FriendRequests", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deutsch (German).
        /// </summary>
        public static string LanguageGroupGerman {
            get {
                return ResourceManager.GetString("LanguageGroupGerman", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageGroupEnglish {
            get {
                return ResourceManager.GetString("LanguageGroupEnglish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Français (French).
        /// </summary>
        public static string LanguageGroupFrench {
            get {
                return ResourceManager.GetString("LanguageGroupFrench", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other Languages.
        /// </summary>
        public static string LanguageGroupOther {
            get {
                return ResourceManager.GetString("LanguageGroupOther", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Español (Spanish).
        /// </summary>
        public static string LanguageGroupSpanish {
            get {
                return ResourceManager.GetString("LanguageGroupSpanish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language &amp; Region.
        /// </summary>
        public static string LanguageRegion {
            get {
                return ResourceManager.GetString("LanguageRegion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your preferred language and regional format for the user interface..
        /// </summary>
        public static string LanguageRegionHelpText {
            get {
                return ResourceManager.GetString("LanguageRegionHelpText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mentions.
        /// </summary>
        public static string Mentions {
            get {
                return ResourceManager.GetString("Mentions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name Display.
        /// </summary>
        public static string NameDisplay {
            get {
                return ResourceManager.GetString("NameDisplay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First Name + Last Initial (John S.).
        /// </summary>
        public static string NameDisplayFirstNameLastInitial {
            get {
                return ResourceManager.GetString("NameDisplayFirstNameLastInitial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First Name Only (John).
        /// </summary>
        public static string NameDisplayFirstName {
            get {
                return ResourceManager.GetString("NameDisplayFirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full Name (John Smith).
        /// </summary>
        public static string NameDisplayFullName {
            get {
                return ResourceManager.GetString("NameDisplayFullName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How your name appears to other users across the site..
        /// </summary>
        public static string NameDisplayHelpText {
            get {
                return ResourceManager.GetString("NameDisplayHelpText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username (johnsmith).
        /// </summary>
        public static string NameDisplayUsername {
            get {
                return ResourceManager.GetString("NameDisplayUsername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notification Auto-Expiration (in days).
        /// </summary>
        public static string NotificationExpiration {
            get {
                return ResourceManager.GetString("NotificationExpiration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notifications older than this will automatically expire and can be cleaned up. Set to 365 days to keep them for a year..
        /// </summary>
        public static string NotificationExpirationHelpText {
            get {
                return ResourceManager.GetString("NotificationExpirationHelpText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Post Comments.
        /// </summary>
        public static string PostComments {
            get {
                return ResourceManager.GetString("PostComments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Post Reactions.
        /// </summary>
        public static string PostReactions {
            get {
                return ResourceManager.GetString("PostReactions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your preferences have been reset to defaults successfully..
        /// </summary>
        public static string PreferencesResetSuccess {
            get {
                return ResourceManager.GetString("PreferencesResetSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your preferences have been saved successfully..
        /// </summary>
        public static string PreferencesSavedSuccess {
            get {
                return ResourceManager.GetString("PreferencesSavedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        public static string ResetToDefaults {
            get {
                return ResourceManager.GetString("ResetToDefaults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Preferences.
        /// </summary>
        public static string SavePreferences {
            get {
                return ResourceManager.GetString("SavePreferences", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System Notifications.
        /// </summary>
        public static string SystemNotifications {
            get {
                return ResourceManager.GetString("SystemNotifications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other Common Timezones.
        /// </summary>
        public static string TimezoneGroupOther {
            get {
                return ResourceManager.GetString("TimezoneGroupOther", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        public static string TimezoneGroupUS {
            get {
                return ResourceManager.GetString("TimezoneGroupUS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your preferred timezone for displaying dates and times..
        /// </summary>
        public static string TimezoneHelpText {
            get {
                return ResourceManager.GetString("TimezoneHelpText", resourceCulture);
            }
        }
    }
}