//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Shared {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FriendProfileHeader {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FriendProfileHeader() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Shared.FriendProfileHeader", typeof(FriendProfileHeader).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        public static string FriendSingular {
            get {
                return ResourceManager.GetString("FriendSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string FriendPlural {
            get {
                return ResourceManager.GetString("FriendPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mutual.
        /// </summary>
        public static string Mutual {
            get {
                return ResourceManager.GetString("Mutual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Posts.
        /// </summary>
        public static string GroupPosts {
            get {
                return ResourceManager.GetString("GroupPosts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string PostSingular {
            get {
                return ResourceManager.GetString("PostSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string PostPlural {
            get {
                return ResourceManager.GetString("PostPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupSingular {
            get {
                return ResourceManager.GetString("GroupSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string GroupPlural {
            get {
                return ResourceManager.GetString("GroupPlural", resourceCulture);
            }
        }
    }
}
