//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Shared {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImageUploadModal {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageUploadModal() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Shared.ImageUploadModal", typeof(ImageUploadModal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add {0} Image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add {0} Images.
        /// </summary>
        public static string AddImages {
            get {
                return ResourceManager.GetString("AddImages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click to select images or drag and drop.
        /// </summary>
        public static string DropAreaText {
            get {
                return ResourceManager.GetString("DropAreaText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum of {0} images allowed..
        /// </summary>
        public static string MaxImagesError {
            get {
                return ResourceManager.GetString("MaxImagesError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} is not an image..
        /// </summary>
        public static string NotAnImageError {
            get {
                return ResourceManager.GetString("NotAnImageError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove image.
        /// </summary>
        public static string RemoveImage {
            get {
                return ResourceManager.GetString("RemoveImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected Images.
        /// </summary>
        public static string SelectedImages {
            get {
                return ResourceManager.GetString("SelectedImages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Images.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You selected too many files. Please select up to {0} image(s)..
        /// </summary>
        public static string TooManyFilesError {
            get {
                return ResourceManager.GetString("TooManyFilesError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Up to {0} images • PNG, JPG, GIF • Max {1}MB each.
        /// </summary>
        public static string UploadHint {
            get {
                return ResourceManager.GetString("UploadHint", resourceCulture);
            }
        }
    }
}
