//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Shared {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MoreFunctions {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MoreFunctions() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Shared.MoreFunctions", typeof(MoreFunctions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create a new group.
        /// </summary>
        public static string CreateGroupTooltip {
            get {
                return ResourceManager.GetString("CreateGroupTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create New Group.
        /// </summary>
        public static string CreateNewGroup {
            get {
                return ResourceManager.GetString("CreateNewGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating....
        /// </summary>
        public static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the group..
        /// </summary>
        public static string GroupCreationFailed {
            get {
                return ResourceManager.GetString("GroupCreationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group "{0}" has been created successfully!.
        /// </summary>
        public static string GroupCreatedSuccess {
            get {
                return ResourceManager.GetString("GroupCreatedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GroupDescription {
            get {
                return ResourceManager.GetString("GroupDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group description is required..
        /// </summary>
        public static string GroupDescriptionRequired {
            get {
                return ResourceManager.GetString("GroupDescriptionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group name is required..
        /// </summary>
        public static string GroupNameRequired {
            get {
                return ResourceManager.GetString("GroupNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No additional functions available..
        /// </summary>
        public static string NoFunctionsAvailable {
            get {
                return ResourceManager.GetString("NoFunctionsAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to create a group..
        /// </summary>
        public static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Public Group.
        /// </summary>
        public static string PublicGroup {
            get {
                return ResourceManager.GetString("PublicGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Public groups are visible to all users and can be found in search..
        /// </summary>
        public static string PublicGroupHelp {
            get {
                return ResourceManager.GetString("PublicGroupHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hidden Group.
        /// </summary>
        public static string HiddenGroup {
            get {
                return ResourceManager.GetString("HiddenGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hidden groups cannot be found in searches. Members can only be added by group administrators..
        /// </summary>
        public static string HiddenGroupHelp {
            get {
                return ResourceManager.GetString("HiddenGroupHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Require Join Approval.
        /// </summary>
        public static string RequireJoinApproval {
            get {
                return ResourceManager.GetString("RequireJoinApproval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New members must be approved by an administrator before joining..
        /// </summary>
        public static string RequireJoinApprovalHelp {
            get {
                return ResourceManager.GetString("RequireJoinApprovalHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Require Agreement to Group Rules.
        /// </summary>
        public static string RequireAcceptRules {
            get {
                return ResourceManager.GetString("RequireAcceptRules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users must agree to the group rules before joining or submitting a join request..
        /// </summary>
        public static string RequireAcceptRulesHelp {
            get {
                return ResourceManager.GetString("RequireAcceptRulesHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable Points System.
        /// </summary>
        public static string EnablePointsSystem {
            get {
                return ResourceManager.GetString("EnablePointsSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Members earn points for posts, comments, and likes. Members can achieve Rising Contributor, Top Contributor, and All-star Contributor badges..
        /// </summary>
        public static string EnablePointsSystemHelp {
            get {
                return ResourceManager.GetString("EnablePointsSystemHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More Functions.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
