//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Shared {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TimeFormatting {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeFormatting() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Shared.TimeFormatting", typeof(TimeFormatting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}d ago.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to expires in {0}d.
        /// </summary>
        public static string ExpiresInDays {
            get {
                return ResourceManager.GetString("ExpiresInDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to expires in {0}h.
        /// </summary>
        public static string ExpiresInHours {
            get {
                return ResourceManager.GetString("ExpiresInHours", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to expires in {0}m.
        /// </summary>
        public static string ExpiresInMinutes {
            get {
                return ResourceManager.GetString("ExpiresInMinutes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to expires in {0}w.
        /// </summary>
        public static string ExpiresInWeeks {
            get {
                return ResourceManager.GetString("ExpiresInWeeks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to expires {0}.
        /// </summary>
        public static string ExpiresOn {
            get {
                return ResourceManager.GetString("ExpiresOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to expires soon.
        /// </summary>
        public static string ExpiresSoon {
            get {
                return ResourceManager.GetString("ExpiresSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}h ago.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}m ago.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}mo ago.
        /// </summary>
        public static string MonthsAgo {
            get {
                return ResourceManager.GetString("MonthsAgo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}w ago.
        /// </summary>
        public static string WeeksAgo {
            get {
                return ResourceManager.GetString("WeeksAgo", resourceCulture);
            }
        }
    }
}
