//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Notifications {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationTemplates {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationTemplates() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Notifications.NotificationTemplates", typeof(NotificationTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; reacted to your comment with {1}.
        /// </summary>
        public static string CommentReaction {
            get {
                return ResourceManager.GetString("CommentReaction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; replied to your comment.
        /// </summary>
        public static string CommentReply {
            get {
                return ResourceManager.GetString("CommentReply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; accepted your friend request.
        /// </summary>
        public static string FriendAccepted {
            get {
                return ResourceManager.GetString("FriendAccepted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; sent you a friend request.
        /// </summary>
        public static string FriendRequest {
            get {
                return ResourceManager.GetString("FriendRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; reacted to your comment in a group with {1}.
        /// </summary>
        public static string GroupCommentReaction {
            get {
                return ResourceManager.GetString("GroupCommentReaction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; replied to your comment in a group.
        /// </summary>
        public static string GroupCommentReply {
            get {
                return ResourceManager.GetString("GroupCommentReply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; commented on your group post.
        /// </summary>
        public static string GroupPostComment {
            get {
                return ResourceManager.GetString("GroupPostComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; reacted to your group post with {1}.
        /// </summary>
        public static string GroupPostReaction {
            get {
                return ResourceManager.GetString("GroupPostReaction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; commented on your post.
        /// </summary>
        public static string PostComment {
            get {
                return ResourceManager.GetString("PostComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; reacted to your post with {1}.
        /// </summary>
        public static string PostReaction {
            get {
                return ResourceManager.GetString("PostReaction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to angry.
        /// </summary>
        public static string ReactionAngry {
            get {
                return ResourceManager.GetString("ReactionAngry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to care.
        /// </summary>
        public static string ReactionCare {
            get {
                return ResourceManager.GetString("ReactionCare", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to haha.
        /// </summary>
        public static string ReactionHaha {
            get {
                return ResourceManager.GetString("ReactionHaha", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to like.
        /// </summary>
        public static string ReactionLike {
            get {
                return ResourceManager.GetString("ReactionLike", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to love.
        /// </summary>
        public static string ReactionLove {
            get {
                return ResourceManager.GetString("ReactionLove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sad.
        /// </summary>
        public static string ReactionSad {
            get {
                return ResourceManager.GetString("ReactionSad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wow.
        /// </summary>
        public static string ReactionWow {
            get {
                return ResourceManager.GetString("ReactionWow", resourceCulture);
            }
        }
    }
}
