//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Groups {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BannedMembersTab {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BannedMembersTab() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Groups.BannedMembersTab", typeof(BannedMembersTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string SearchPlaceholder {
            get { return ResourceManager.GetString("SearchPlaceholder", resourceCulture); }
        }

        public static string LoadingBannedMembers {
            get { return ResourceManager.GetString("LoadingBannedMembers", resourceCulture); }
        }

        public static string NoBannedMembers {
            get { return ResourceManager.GetString("NoBannedMembers", resourceCulture); }
        }

        public static string Banned {
            get { return ResourceManager.GetString("Banned", resourceCulture); }
        }

        public static string UnbanMember {
            get { return ResourceManager.GetString("UnbanMember", resourceCulture); }
        }

        public static string Loading {
            get { return ResourceManager.GetString("Loading", resourceCulture); }
        }

        public static string LoadMoreBannedMembers {
            get { return ResourceManager.GetString("LoadMoreBannedMembers", resourceCulture); }
        }

        public static string BannedOn {
            get { return ResourceManager.GetString("BannedOn", resourceCulture); }
        }

        public static string UnbanDescription {
            get { return ResourceManager.GetString("UnbanDescription", resourceCulture); }
        }

        public static string NoPermissionToUnban {
            get { return ResourceManager.GetString("NoPermissionToUnban", resourceCulture); }
        }

        public static string ShowingBannedMembersSingular {
            get { return ResourceManager.GetString("ShowingBannedMembersSingular", resourceCulture); }
        }

        public static string ShowingBannedMembersPlural {
            get { return ResourceManager.GetString("ShowingBannedMembersPlural", resourceCulture); }
        }

        public static string MoreAvailable {
            get { return ResourceManager.GetString("MoreAvailable", resourceCulture); }
        }
    }
}
