//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Groups {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GroupAdministrationModal {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupAdministrationModal() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Groups.GroupAdministrationModal", typeof(GroupAdministrationModal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        public static string BannedMembers {
            get {
                return ResourceManager.GetString("BannedMembers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View and manage banned members..
        /// </summary>
        public static string BannedMembersDescription {
            get {
                return ResourceManager.GetString("BannedMembersDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Banned member management features will be available in a future update..
        /// </summary>
        public static string BannedMembersPlaceholder {
            get {
                return ResourceManager.GetString("BannedMembersPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading administration data..
        /// </summary>
        public static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string GroupSettings {
            get {
                return ResourceManager.GetString("GroupSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Advanced group configuration options..
        /// </summary>
        public static string GroupSettingsDescription {
            get {
                return ResourceManager.GetString("GroupSettingsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Advanced settings features will be available in a future update..
        /// </summary>
        public static string GroupSettingsPlaceholder {
            get {
                return ResourceManager.GetString("GroupSettingsPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Join Requests.
        /// </summary>
        public static string JoinRequests {
            get {
                return ResourceManager.GetString("JoinRequests", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Review and approve pending join requests..
        /// </summary>
        public static string JoinRequestsDescription {
            get {
                return ResourceManager.GetString("JoinRequestsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Join request management features will be available in a future update..
        /// </summary>
        public static string JoinRequestsPlaceholder {
            get {
                return ResourceManager.GetString("JoinRequestsPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string MemberManagement {
            get {
                return ResourceManager.GetString("MemberManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View and manage group members..
        /// </summary>
        public static string MemberManagementDescription {
            get {
                return ResourceManager.GetString("MemberManagementDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Member management features will be available in a future update..
        /// </summary>
        public static string MemberManagementPlaceholder {
            get {
                return ResourceManager.GetString("MemberManagementPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RoleManagement {
            get {
                return ResourceManager.GetString("RoleManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assign administrator and moderator roles to members..
        /// </summary>
        public static string RoleManagementDescription {
            get {
                return ResourceManager.GetString("RoleManagementDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role management features will be available in a future update..
        /// </summary>
        public static string RoleManagementPlaceholder {
            get {
                return ResourceManager.GetString("RoleManagementPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Administration.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
