//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Groups {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GroupSettingsModal {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupSettingsModal() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Groups.GroupSettingsModal", typeof(GroupSettingsModal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable Points System.
        /// </summary>
        public static string EnablePointsSystem {
            get {
                return ResourceManager.GetString("EnablePointsSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Members earn points for posts, comments, and likes. Members can achieve Rising Contributor, Top Contributor, and All-star Contributor badges..
        /// </summary>
        public static string EnablePointsSystemHelp {
            get {
                return ResourceManager.GetString("EnablePointsSystemHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hidden from Discovery.
        /// </summary>
        public static string HiddenFromDiscovery {
            get {
                return ResourceManager.GetString("HiddenFromDiscovery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hidden groups don't appear in search results..
        /// </summary>
        public static string HiddenFromDiscoveryHelp {
            get {
                return ResourceManager.GetString("HiddenFromDiscoveryHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Public Group.
        /// </summary>
        public static string PublicGroup {
            get {
                return ResourceManager.GetString("PublicGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Public groups are visible to all users..
        /// </summary>
        public static string PublicGroupHelp {
            get {
                return ResourceManager.GetString("PublicGroupHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Require Join Approval.
        /// </summary>
        public static string RequireJoinApproval {
            get {
                return ResourceManager.GetString("RequireJoinApproval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New members must be approved before joining..
        /// </summary>
        public static string RequireJoinApprovalHelp {
            get {
                return ResourceManager.GetString("RequireJoinApprovalHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Require Agreement to Group Rules.
        /// </summary>
        public static string RequireAcceptRules {
            get {
                return ResourceManager.GetString("RequireAcceptRules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users must agree to the group rules before joining or submitting a join request..
        /// </summary>
        public static string RequireAcceptRulesHelp {
            get {
                return ResourceManager.GetString("RequireAcceptRulesHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Status.
        /// </summary>
        public static string GroupStatusSection {
            get {
                return ResourceManager.GetString("GroupStatusSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When active, the group is ready to accept users and content. Inactive groups are only visible to administrators..
        /// </summary>
        public static string IsActiveHelp {
            get {
                return ResourceManager.GetString("IsActiveHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group is Permanently Closed.
        /// </summary>
        public static string IsClosed {
            get {
                return ResourceManager.GetString("IsClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning: Closing a group is permanent. No changes can be made once closed, even by administrators..
        /// </summary>
        public static string IsClosedHelp {
            get {
                return ResourceManager.GetString("IsClosedHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Settings.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
