//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Groups {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GroupModerationModal {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupModerationModal() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Groups.GroupModerationModal", typeof(GroupModerationModal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading moderation data..
        /// </summary>
        public static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mod Log.
        /// </summary>
        public static string ModerationLog {
            get {
                return ResourceManager.GetString("ModerationLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View history of moderation actions..
        /// </summary>
        public static string ModerationLogDescription {
            get {
                return ResourceManager.GetString("ModerationLogDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderation log features will be available in a future update..
        /// </summary>
        public static string ModerationLogPlaceholder {
            get {
                return ResourceManager.GetString("ModerationLogPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string PendingApproval {
            get {
                return ResourceManager.GetString("PendingApproval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Review posts awaiting moderator approval..
        /// </summary>
        public static string PendingApprovalDescription {
            get {
                return ResourceManager.GetString("PendingApprovalDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pending approval features will be available in a future update..
        /// </summary>
        public static string PendingApprovalPlaceholder {
            get {
                return ResourceManager.GetString("PendingApprovalPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string RecentPosts {
            get {
                return ResourceManager.GetString("RecentPosts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse recent posts for moderation review..
        /// </summary>
        public static string RecentPostsDescription {
            get {
                return ResourceManager.GetString("RecentPostsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recent posts review features will be available in a future update..
        /// </summary>
        public static string RecentPostsPlaceholder {
            get {
                return ResourceManager.GetString("RecentPostsPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reported.
        /// </summary>
        public static string ReportedContent {
            get {
                return ResourceManager.GetString("ReportedContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Review content that has been reported by members..
        /// </summary>
        public static string ReportedContentDescription {
            get {
                return ResourceManager.GetString("ReportedContentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reported content features will be available in a future update..
        /// </summary>
        public static string ReportedContentPlaceholder {
            get {
                return ResourceManager.GetString("ReportedContentPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Moderation.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
