//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.Groups {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RulesAcceptanceModal {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RulesAcceptanceModal() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.Groups.RulesAcceptanceModal", typeof(RulesAcceptanceModal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Agree &amp; Join.
        /// </summary>
        public static string AgreeAndJoin {
            get {
                return ResourceManager.GetString("AgreeAndJoin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to I have read and agree to abide by these rules.
        /// </summary>
        public static string AgreeToRules {
            get {
                return ResourceManager.GetString("AgreeToRules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading group rules....
        /// </summary>
        public static string LoadingGroupRules {
            get {
                return ResourceManager.GetString("LoadingGroupRules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading rules....
        /// </summary>
        public static string LoadingRules {
            get {
                return ResourceManager.GetString("LoadingRules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This group has no rules defined yet..
        /// </summary>
        public static string NoRulesDefined {
            get {
                return ResourceManager.GetString("NoRulesDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to These rules help maintain a positive and respectful community environment..
        /// </summary>
        public static string RulesHelp {
            get {
                return ResourceManager.GetString("RulesHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Before joining this group, please read and agree to the following rules:.
        /// </summary>
        public static string RulesIntro {
            get {
                return ResourceManager.GetString("RulesIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Rules.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
