//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.SocialFeed {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PostEditModal {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostEditModal() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.SocialFeed.PostEditModal", typeof(PostEditModal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string EditPost {
            get { return ResourceManager.GetString("EditPost", resourceCulture); }
        }

        public static string AddEmoji {
            get { return ResourceManager.GetString("AddEmoji", resourceCulture); }
        }

        public static string PostImage {
            get { return ResourceManager.GetString("PostImage", resourceCulture); }
        }

        public static string NewImage {
            get { return ResourceManager.GetString("NewImage", resourceCulture); }
        }

        public static string CancelChanges {
            get { return ResourceManager.GetString("CancelChanges", resourceCulture); }
        }

        public static string SaveChanges {
            get { return ResourceManager.GetString("SaveChanges", resourceCulture); }
        }

        public static string Saving {
            get { return ResourceManager.GetString("Saving", resourceCulture); }
        }
    }
}
