//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSpeakWeb.Resources.SocialFeed {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UnifiedArticle {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnifiedArticle() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSpeakWeb.Resources.SocialFeed.UnifiedArticle", typeof(UnifiedArticle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string PublicPostsWarningBold {
            get { return ResourceManager.GetString("PublicPostsWarningBold", resourceCulture); }
        }

        public static string PublicPostsWarningDetail {
            get { return ResourceManager.GetString("PublicPostsWarningDetail", resourceCulture); }
        }

        public static string PublicPostsConfirmQuestion {
            get { return ResourceManager.GetString("PublicPostsConfirmQuestion", resourceCulture); }
        }

        public static string Cancel {
            get { return ResourceManager.GetString("Cancel", resourceCulture); }
        }

        public static string YesMakePublic {
            get { return ResourceManager.GetString("YesMakePublic", resourceCulture); }
        }
    }
}
